[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/admin/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/admin/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/assets/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/assets/:splat"
  status = 200

[[redirects]]
  from = "/onboard/*"
  to = "https://banded-overcherished-darby.ngrok-free.dev/onboard/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/onboard/:token/success"
  to = "https://banded-overcherished-darby.ngrok-free.dev/onboard/:token/success"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200